### ISSUE TITLE
Hide Previous / Next labels 

### ISSUE THREAD

**Issue by eitanavgil** [lucasmogari/react-pagination#5]
Add the ability to hide the `Previous` and `Next` labels but keep the buttons with `<` and `>` 

This can help in layouts that has less space to show the pagination. 

(it is important to keep `aria-label` on these button to make it accessible) 

P.S. - I will be happy to help and suggest a PR, but I am having technical issues with running the project. If you want to assist me - I can try to make this happen

**Comment by lucasmogari** [comment]
Hi! The pagination components are up to you to style and build. You can create those buttons with arrows only. Check the example on the site. If you have more questions, please feel free to ask.
